Update Diana README with new documentation for 0.0.6a10
NeonGeckoCom/neon-diana-utils pull request #31
Opened 2023-06-09 16:40 UTC by erikabarcott

# Description
Add new documentation for 0.0.6a10 to Diana README.

# Issues

# Other Notes
I incorporated all your changes from [your gist version](https://gist.github.com/NeonDaniel/299a4407d914b97d6ad5debc2a4618e5/d27e0513b598780e307a0e47f9cb45eeef8e768c), but I slightly reworded the Let's Encrypt bits.

2023-06-12 16:54 UTC, NeonDaniel commented
Rendered doc viewable at: https://github.com/erikabarcott/neon-diana-utils/tree/new-diana-docs

2023-06-12 16:59 UTC, NeonDaniel requested changes

2023-06-12 16:59 UTC, NeonDaniel commented on README.md
> +* [Neon Skill Utilities](https://github.com/NeonGeckoCom/neon-utils) 1.0 or later.
This shouldn't be necessary to install separately; was there an with with dependencies after installing just diana?

2023-06-12 16:59 UTC, NeonDaniel commented on README.md
> +**Warning:** You can use `pip install neon-diana-utils` to install the current stable version. However, that version does not include Helm chart support. For information on installing and running the
Maybe update this note to indicate that Helm support is (will be?) added in version `0.1.0` so we don't have to edit it before release

2023-06-12 16:59 UTC, NeonDaniel commented on README.md
> +diana --help
Consider `diana --version` here so the version can be verified

2023-06-12 18:11 UTC, NeonDaniel commented on README.md
> +* [Neon Skill Utilities](https://github.com/NeonGeckoCom/neon-utils) 1.0 or later.
You shouldn't have to touch `neon-utils` at all; if you do then its something I should fix in `neon-diana-utils`

2023-06-16 00:41 UTC, NeonClary requested changes
Two tiny proofreading changes. The content is beyond my technical capabilities, but it makes sense and seems well organized.

2023-06-16 00:41 UTC, NeonClary commented on README.md
> +This example deployes Diana in a local [Microk8s Kubernetes](https://microk8s.io/) cluster.
Deployes --> deploys

2023-06-16 14:05 UTC, erikabarcott commented on README.md
> +**Warning:** You can use `pip install neon-diana-utils` to install the current stable version. Version 0.1.0 includes Helm chart support. For information on installing and running older versions, see
Exciting idea! I agree, I think it's ready for a 1.x but I'll leave it to you @NeonDaniel

2023-06-16 14:07 UTC, erikabarcott commented on README.md
> +This example deployes Diana in a local [Microk8s Kubernetes](https://microk8s.io/) cluster.
Thank you!!

2023-06-30 02:00 UTC, NeonDaniel commented on README.md
> +**Warning:** You can use `pip install neon-diana-utils` to install the current stable version. Version 0.1.0 includes Helm chart support. For information on installing and running older versions, see
Makes sense; I went ahead and cleaned up all of the deprecated methods, so we should push a 1.0.0 release next anyways (https://semver.org/spec/v2.0.0.html)

2023-06-30 20:29 UTC, merged